language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - travis_retry composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction

script: composer test
